[package]
name = "nexkvm-storage"
description = "Configuration format and persistent storage for nexkvm."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
nexkvm-core.workspace = true
nexkvm-crypto.workspace = true
nexkvm-telemetry.workspace = true
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
