[package]
name = "nexkvm-gui"
description = "Cross-platform graphical control panel for nexkvm."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "nexkvm-gui"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
nexkvm-storage.workspace = true
eframe.workspace = true
